### ISSUE TITLE
Not work for me

### ISSUE THREAD

**Issue by yantrab** [keenondrums/angular-builder-custom-terser-options#1]
I did step by step you instruction,  can you help me with that?

[source](https://github.com/yantrab/nest-angular/blob/master/client/angular.json)

**Comment by keenondrums** [comment]
@yantrab does it produce any error? Or it compiles without any error, but your custom terserOptions are not applied?

**Comment by keenondrums** [comment]
@yantrab could you try running `npm i -D @angular-devkit/build-angular^0.13.2`?
I see you're using @angular-devkit/build-angular~0.12.0 which I did not test this builder with.

**Comment by yantrab** [comment]
Hi, thanks for your answer.

I updated the module, with the same result. 
no error in compilation, but there is problem with class names.

**Comment by keenondrums** [comment]
@yantrab what command do you execute?
I tried to clone your repo, wen to 'client' folder and ran `ng build --prod`.
I received a bunch of errors which prevent it from being compiled.
```
ERROR in app/starter.module.ts(36,35): Error during template compile of 'AppModule'
  Could not resolve src/api/http.service relative to [object Object]..
src/app/auth/auth.service.ts(1,32): error TS2307: Cannot find module 'src/api/auth.controller'.
../shared/models/user.model.ts(1,45): error TS2307: Cannot find module 'class-validator'.
src/app/guard.ts(14,46): error TS2339: Property 'getUserAuthenticated' does not exist on type 'AuthService'.
src/app/starter.module.ts(11,28): error TS2307: Cannot find module 'src/api/http.service'.
src/dyna-form/property.utils.ts(1,28): error TS2307: Cannot find module 'class-transformer'.
src/dyna-form/dyna.validator.ts(2,45): error TS2307: Cannot find module 'class-validator'.
src/dyna-form/dyna-form.builder.ts(4,26): error TS2307: Cannot find module 'class-validator'.
src/app/auth/auth.component.ts(8,32): error TS2307: Cannot find module 'src/api/i18n/login.i18n'.
src/app/auth/auth.component.ts(29,24): error TS2339: Property 'login' does not exist on type 'AuthService'.
src/app/auth/auth.module.ts(7,32): error TS2307: Cannot find module 'src/api/auth.controller'.
```
I'm not sure how you got around this and made it pas these errors to see that this builder doesn't work.

**Comment by yantrab** [comment]
Hi, tanks for you help.

you need to run npm i in root folder, to generate client api.

**Comment by keenondrums** [comment]
@yantrab in your tsconfig.json you set `target` to `es5`. In this case all classes are converted to functions. You have two options here:
- Change `target` from `es5` to `es6`
- In you angular.json under `terserOptions` replace `keep_classnames` with `keep_fnames`

**Comment by yantrab** [comment]
Perfect , thanks!

**Comment by keenondrums** [comment]
Happy to help!
