### ISSUE TITLE
Exlcude and include filters

### ISSUE THREAD

**Issue by lppedd** [keenondrums/angular-builder-custom-terser-options#4]
Is it possible to set include and exclude filters for Terser?  
Looking at the source code it doesn't seem so. If it is feasible I'll do it.

**Comment by lppedd** [comment]
Nevermind, not feasible. Filters don't work.

**Comment by keenondrums** [comment]
Nevertheless, you should be able to pass any supported [terserOptions](https://github.com/webpack-contrib/terser-webpack-plugin#terseroptions). Unfortunately, [include and exclude](https://github.com/webpack-contrib/terser-webpack-plugin#include) live one level higher in TerserPlugin config, thus not supported.

**Comment by lppedd** [comment]
@keenondrums I managed to set them extending your code, however filters act on bundles, not on sigle sources, that's why it's not working.
