### ISSUE TITLE
Could not find the implem entation for builder

### ISSUE THREAD

**Issue by fredrik-macrobond** [keenondrums/angular-builder-custom-terser-options#5]
Neither dev serve or production build works. Angular.json set up according to your example with keep_classnames set to true.

Package.json:

{
  "name": "mbnet",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve --proxy-config proxy.config.json",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "readme": "removed dependencies: generator-code yo toastr",
  "private": true,
  "dependencies": {
    "@angular/animations": "9.0.0-next.3",
    "@angular/cdk": "^8.1.4",
    "@angular/common": "9.0.0-next.3",
    "@angular/compiler": "9.0.0-next.3",
    "@angular/core": "9.0.0-next.3",
    "@angular/forms": "9.0.0-next.3",
    "@angular/material": "^8.1.4",
    "@angular/platform-browser": "9.0.0-next.3",
    "@angular/platform-browser-dynamic": "9.0.0-next.3",
    "@angular/router": "9.0.0-next.3",
    "@angular/service-worker": "9.0.0-next.3",
    "classlist.js": "^1.1.20150312",
    "core-js": "^3.1.4",
    "oidc-client": "^1.9.0",
    "rxjs": "6.5.2",
    "tslib": "^1.10.0",
    "zone.js": "^0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "0.803.0",
    "@angular/cli": "^8.3.0",
    "@angular/compiler-cli": "9.0.0-next.3",
    "@angular/language-service": "^9.0.0-next.3",
    "@types/jasmine": "^3.4.0",
    "@types/jasminewd2": "~2.0.6",
    "@types/node": "^12.7.2",
    "angular-builder-custom-terser-options": "^1.0.1",
    "codelyzer": "^5.1.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.2.0",
    "karma-chrome-launcher": "^3.1.0",
    "karma-cli": "~2.0.0",
    "karma-coverage-istanbul-reporter": "^2.1.0",
    "karma-jasmine": "^2.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "protractor": "^5.4.2",
    "rxjs-tslint": "^0.1.7",
    "ts-node": "^8.3.0",
    "tslint": "^5.19.0",
    "typescript": "3.5.3"
  },
  "browserslist": [
    "> 0.5%",
    "last 3 versions",
    "not dead",
    "IE 11"
  ]
}

**Comment by keenondrums** [comment]
As far as I can see you're using Angular 8 which is not supported now. See #3. Actually, support for Angular 8 is in master. I did not have a chance to properly test, so I did not publish it yet. You can try to pull the code directly from master or wait for the official release.
